
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 859195 bytes/channel
 *	Total Size: 1 * 859195 + 4 (header) = 859239 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	gameSong.wav
 *	Time-stamp: Wed Apr 22 20:13:47 2020
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 859195

extern const unsigned char gameSong[859195];

#endif /* __GAMESONGH__ */
