
/**************************************************************
 *	
 *	loseSound, 8 bit, 11025Hz,
 *	1 channel, 55831 bytes/channel
 *	Total Size: 1 * 55831 + 4 (header) = 55875 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	loseSound.wav
 *	Time-stamp: Wed Apr 22 21:38:59 2020
 *	
 **************************************************************/

#ifndef __LOSESOUNDH__
#define __LOSESOUNDH__

#define LOSESOUNDFREQ 11025
#define LOSESOUNDLEN 55831

extern const unsigned char loseSound[55831];

#endif /* __LOSESOUNDH__ */
